# Generated by Django 2.1.4 on 2020-01-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190509_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(default=123, max_length=200, verbose_name='ระดับ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(default='123', max_length=200, verbose_name='เบอร์โทร'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='members.Customer', verbose_name='ลูกค้า'),
        ),
    ]
